#!/bin/sh -e

DKMS_NAME="ntsync"
DKMS_VERSION="6.14.0"

case "$1" in
configure)
	dkms add -m $DKMS_NAME -v $DKMS_VERSION
	dkms build -m $DKMS_NAME -v $DKMS_VERSION
	dkms install -m $DKMS_NAME -v $DKMS_VERSION
	modprobe ntsync
	;;
esac
